version: 2
updates:
  - package-ecosystem: github-actions
    directories: ["/", "/.github/actions/terraform-init"]
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: terraform
    directories: ["/environments/dev", "/environments/prod", "/bootstrap/dev", "/bootstrap/prod"]
    schedule:
      interval: weekly
    groups:
      terraform-providers:
        patterns: ["*"]
